import React, { useEffect, useState } from 'react';
import {createRoot} from 'react-dom/client';
import {BoxMouseOrganique,LiquidParallax} from '../src/index.js';
import './style.css';
import './experiments.css';
import { experiments, ExperimentCards, ExperimentPage } from './Experiments.jsx';

const links=[['/','Collection'],['/reveal','Organic reveal'],['/parallax','Liquid parallax'],['/guide','Guide']];
function App(){
  const [path,setPath]=useState(location.pathname);
  useEffect(()=>{const pop=()=>setPath(location.pathname);window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);
  useEffect(()=>{document.title=`${(links.find(([p])=>p===path)?.[1] || experiments.find(e=>'/'+e.slug===path)?.title)||'Introuvable'} — Organic`;window.scrollTo(0,0);},[path]);
  function navigate(e){const a=e.target.closest('a');if(!a||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||e.button!==0||a.origin!==location.origin)return;e.preventDefault();history.pushState({},'',a.pathname);setPath(a.pathname);}
  return <div onClick={navigate}><header><a className="brand" href="/">organic<span>INTERACTION TOOLBOX</span></a><nav aria-label="Navigation principale">{links.map(([url,label])=><a key={url} href={url} aria-current={path===url?'page':undefined}>{label}</a>)}<select className="component-menu" aria-label="Autres composants" value={experiments.some(e=>'/'+e.slug===path)?path:''} onChange={e=>{if(e.target.value){history.pushState({},'',e.target.value);setPath(e.target.value)}}}><option value="" disabled>Autres composants</option>{experiments.map(e=><option key={e.slug} value={'/'+e.slug}>{e.title}</option>)}</select></nav><span className="version">EXPERIMENTS / 001—016</span></header><main key={path}>{path==='/'?<Home/>:path==='/reveal'?<Playground kind="reveal"/>:path==='/parallax'?<Playground kind="parallax"/>:path==='/guide'?<Guide/>:experiments.some(e=>'/'+e.slug===path)?<ExperimentPage item={experiments.find(e=>'/'+e.slug===path)}/>:<section className="intro"><h1>Page introuvable.</h1><a href="/">Retour à la collection ↗</a></section>}</main><footer><span>ORGANIC / MADE TO FEEL DIFFERENT</span><a href="https://github.com/Seeky-s/mouse-reveal-organique">Le package d’origine ↗</a></footer></div>;
}
function Home(){return <><section className="intro"><p className="eyebrow">UNE COLLECTION D’INTERACTIONS REACT</p><div className="intro-row"><h1>Make the web<br/>feel <em>alive.</em></h1><p>Des images qui réagissent.<br/>Des interfaces qui prennent vie.<br/><span>Seize composants. À explorer, à ajuster, à intégrer.</span></p></div></section><section className="collection" aria-label="Composants"><article><BoxMouseOrganique className="card" img_cover="/cover.svg" img_background="/reveal.svg"><span className="topline">01 / REVEAL</span><div><h2>Another world,<br/><em>underneath.</em></h2><a className="pill" href="/reveal">Explorer le reveal ↗</a></div></BoxMouseOrganique><div className="caption"><h3>Organic reveal</h3><span>MASQUE LIQUIDE · CANVAS 2D</span></div></article><article><LiquidParallax className="card" src="/dunes.svg" alt="Dunes abstraites aux couleurs de l’océan"><span className="topline">02 / PARALLAX</span><div><h2>Just below<br/>the <em>surface.</em></h2><a className="pill" href="/parallax">Explorer la parallaxe ↗</a></div></LiquidParallax><div className="caption"><h3>Liquid parallax</h3><span>PROFONDEUR & ONDES · WEBGL</span></div></article></section><ExperimentCards/><section className="manifesto"><p className="eyebrow">LE MOUVEMENT, À VOTRE MESURE</p><h2>Votre contenu.<br/><em>Une nouvelle sensation.</em></h2><p>Des composants indépendants, des réglages simples et du contenu qui reste cliquable. Explorez chaque effet dans son playground, puis récupérez son exemple React.</p><a href="/guide">Comprendre l’intégration ↗</a></section></>}
function Range({name,value,set,min=0,max=1,step=.01}){return <label className="range">{name}<output>{value.toFixed(2)}</output><input type="range" min={min} max={max} step={step} value={value} onChange={e=>set(Number(e.target.value))}/></label>}
function Code({text}){const [status,setStatus]=useState('Copier');async function copy(){try{await navigator.clipboard.writeText(text);setStatus('Copié ✓');}catch{setStatus('Sélectionnez le code');}}return <div className="code"><div><span>REACT / JSX</span><button onClick={copy}>{status}</button></div><pre><code>{text}</code></pre></div>}
function Playground({kind}){
  const reveal=kind==='reveal';const [size,setSize]=useState(1),[trail,setTrail]=useState(2.2),[organic,setOrganic]=useState(1),[depth,setDepth]=useState(.45),[liquid,setLiquid]=useState(.55),[paused,setPaused]=useState(false),[clicks,setClicks]=useState(0),[src,setSrc]=useState('/dunes.svg'),[notice,setNotice]=useState('Votre image reste sur votre appareil.');
  useEffect(()=>()=>{if(src.startsWith('blob:'))URL.revokeObjectURL(src);},[src]);
  const code=reveal?`import { BoxMouseOrganique } from 'organic-toolbox';\n\n<BoxMouseOrganique\n  img_cover="/cover.svg"\n  img_background="/reveal.svg"\n  size_mouse={${size}}\n  trail_duration={${trail}}\n  organic={${organic}}\n  disabled={${paused}}\n  style={{ minHeight: 480 }}\n>\n  <h2>Your content, your CSS.</h2>\n</BoxMouseOrganique>`:`import { LiquidParallax } from 'organic-toolbox';\n\n<LiquidParallax\n  src="/dunes.svg"\n  alt="Paysage de dunes"\n  depth={${depth}}\n  liquid={${liquid}}\n  paused={${paused}}\n  style={{ minHeight: 480 }}\n>\n  <h2>Just below the surface.</h2>\n</LiquidParallax>`;
  const content=<><div className="topline"><span>{reveal?'01 / ORGANIC REVEAL':'02 / LIQUID PARALLAX'}</span><span>{reveal?'MOVE TO EXPLORE':'CLICK TO MAKE A WAVE'}</span></div><div className="bottomline"><h2>{reveal?'A different':'A little depth.'}<br/><em>{reveal?'perspective.':'A little drift.'}</em></h2><button className="pill" onClick={()=>setClicks(n=>n+1)}>Contenu cliquable ↗ {clicks>0&&`(${clicks})`}</button></div></>;
  return <><section className="page-intro"><a href="/">← La collection</a><p className="eyebrow">PLAYGROUND / {reveal?'001':'002'}</p><h1>{reveal?'Organic':'Liquid'} <em>{reveal?'reveal.':'parallax.'}</em></h1><p>{reveal?'Un second paysage se révèle sous une trace organique.':'L’image suit votre geste, puis les ondulations se dissipent.'}</p></section><div className="playground">{reveal?<BoxMouseOrganique className="stage" img_cover="/cover.svg" img_background="/reveal.svg" size_mouse={size} trail_duration={trail} organic={organic} disabled={paused}>{content}</BoxMouseOrganique>:<LiquidParallax className="stage" src={src} alt="Image du playground de parallaxe" depth={depth} liquid={liquid} paused={paused}>{content}</LiquidParallax>}<aside><p className="eyebrow">FAITES-LE À VOTRE IMAGE</p>{reveal?<><Range name="Rayon" value={size} set={setSize} min={.25} max={3} step={.05}/><Range name="Traînée (secondes)" value={trail} set={setTrail} min={.2} max={6} step={.1}/><Range name="Organique" value={organic} set={setOrganic} max={2} step={.1}/></>:<><Range name="Profondeur" value={depth} set={setDepth}/><Range name="Ondulations" value={liquid} set={setLiquid}/><div className="presets">{[['Calme',.2,.2],['Fluide',.45,.55],['Profond',.8,.85]].map(([label,d,l])=><button key={label} aria-pressed={depth===d&&liquid===l} onClick={()=>{setDepth(d);setLiquid(l)}}>{label}</button>)}</div><label className="upload">Importer une image ↗<input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>20*1024*1024){setNotice('Maximum : 20 Mo.');return;}const url=URL.createObjectURL(f);const im=new Image();im.src=url;try{await im.decode();setSrc(url);setNotice(f.name);}catch{URL.revokeObjectURL(url);setNotice('Image illisible. Essayez un JPG ou PNG.');}}}/></label><p className="small" role="status">{notice}</p></>}<button className="outline" aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?'Reprendre l’effet':reveal?'Désactiver le reveal':'Mettre en pause'}</button></aside></div><section className="integration"><div><p className="eyebrow">UN COMPOSANT, VOTRE MISE EN PAGE</p><h2>Try it.<br/><em>Make it yours.</em></h2><p>{reveal?'Le composant original de mouse-reveal-organique, intégré tel quel depuis npm.':'Un composant React indépendant, avec nettoyage du moteur au démontage et image statique de secours.'}</p><p className="small">Le code suit les réglages du playground. L’import organic-toolbox utilise le package local de ce projet.</p><a href="/guide">Guide d’installation ↗</a></div><Code text={code}/></section></>;
}
function Guide(){return <><section className="page-intro"><p className="eyebrow">GETTING STARTED</p><h1>Small API.<br/><em>Room to play.</em></h1><p>Seize composants indépendants, une seule collection.</p></section><div className="guide"><section><h2>01 / La toolbox locale</h2><p>Ce projet n’est pas encore publié sur npm. Pour le tester dans une autre application React, compilez et empaquetez la bibliothèque :</p><Code text={'npm install\nnpm run build:lib\nnpm pack\n\n# Dans votre application React :\nnpm install /chemin/organic-toolbox-0.1.0.tgz'}/></section><section><h2>02 / Des imports nommés</h2><Code text={"import { BoxMouseOrganique, LiquidParallax,\n  OrganicButton, OrganicSurface, LiquidTransition,\n  OrganicText, AmbientGradient, OrganicLoader,\n  OrganicDivider, InkSpread, OrganicShadow,\n  LiquidProgress, OrganicSpotlight,\n  OrganicImageCompare, OrganicImageFrame,\n  OrganicSkeleton\n} from 'organic-toolbox';"}/><p>Le reveal utilise la dépendance mouse-reveal-organique 0.1.3. La parallaxe est fournie par cette toolbox. React et React DOM restent des peer dependencies.</p></section><section><h2>03 / Images & dimensions</h2><p>Donnez une hauteur au conteneur. Les images sont recadrées en cover. Pour la parallaxe, utilisez des fichiers locaux ou un serveur autorisant CORS. L’import du playground reste sur votre appareil.</p></section><section><h2>04 / Mouvement & accessibilité</h2><p>La parallaxe est statique avec prefers-reduced-motion. Le reveal réduit son mouvement et affiche la couverture sur les appareils tactiles. Les deux effets gardent le contenu interactif. La profondeur de la parallaxe est une approximation visuelle, sans carte de profondeur.</p></section></div></>}
createRoot(document.getElementById('root')).render(<App/>);
